# Generated by Django 4.2.9 on 2024-02-14 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_comment_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="upvotes",
            field=models.ManyToManyField(
                related_name="blog_upvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="upvotes",
            field=models.ManyToManyField(
                related_name="comment_upvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags_related",
            field=models.ManyToManyField(related_name="tags_related", to="api.tags"),
        ),
    ]
