# Generated by Django 4.2.9 on 2024-02-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_tags_blog_upvotes_comment_upvotes_blog_tags_related"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="upvotes",
        ),
    ]
